AWSTemplateFormatVersion: "2010-09-09"
Description: Create EC2 instance.
Parameters:
  KeyPair:
    Description: SSH key pair
    Type: String
Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-467ca739 # Amazon Linux AMI in N.Virginia
      KeyName: !Ref KeyPair
      SecurityGroupIds:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: A simple example
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open Port 22
      GroupName: LetMeIn
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
Outputs:
  Instance:
    Description: The Public DNS for the EC2 Instance
    Value: !Sub '${Ec2Instance.PublicDnsName}'
